name: Code Quality Check

on: [push]

jobs:
  build:
    name: Code Quality Check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.0]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node Modules
        run: npm install

      - name: AoT Build
        run: npm run build

      - name: Unit Test
        run: npm run test

      - name: Generate Coverage Report
        run: npm run test:cov

      - name: Report coverage
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
